import React, { useState, useRef } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {
  Copy,
  Check,
  Download,
  FileCode,
  CheckCircle2,
  FileText,
  Printer,
  Sparkles,
  BookOpen,
  Info
} from 'lucide-react';

interface ReportViewerProps {
  reportMarkdown: string;
  onReset: () => void;
  documentNames: string[];
}

const SECTION_HEADERS = [
  'Research Objective',
  'Executive Summary',
  'Key Findings',
  'Evidence From Uploaded Sources',
  'Comparison Between Documents',
  'Important Statistics',
  'Methodologies',
  'Limitations',
  'Research Gaps',
  'Final Draft',
  'References',
];

export const ReportViewer: React.FC<ReportViewerProps> = ({
  reportMarkdown,
  onReset,
  documentNames,
}) => {
  const [copied, setCopied] = useState(false);
  const [activeSection, setActiveSection] = useState<string | null>(null);
  const printRef = useRef<HTMLDivElement>(null);

  const handleCopy = () => {
    navigator.clipboard.writeText(reportMarkdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    const blob = new Blob([reportMarkdown], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Research_Report_${new Date().toISOString().slice(0, 10)}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handlePrintPdf = () => {
    const printContent = printRef.current?.innerHTML || '';
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Source-Grounded Research Report</title>
          <style>
            body {
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
              padding: 40px;
              color: #1e293b;
              line-height: 1.6;
              max-width: 900px;
              margin: 0 auto;
            }
            h1 { font-size: 24px; border-bottom: 2px solid #3b82f6; padding-bottom: 8px; margin-top: 28px; color: #0f172a; }
            h2 { font-size: 20px; border-bottom: 1px solid #e2e8f0; padding-bottom: 6px; margin-top: 24px; color: #1e293b; }
            h3 { font-size: 16px; margin-top: 18px; color: #334155; }
            table { width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 13px; }
            th, td { border: 1px solid #cbd5e1; padding: 8px 12px; text-align: left; }
            th { background-color: #f1f5f9; font-weight: 600; }
            blockquote { border-left: 4px solid #3b82f6; background-color: #f8fafc; padding: 8px 16px; margin: 16px 0; font-style: italic; }
            code { background-color: #f1f5f9; padding: 2px 6px; border-radius: 4px; font-family: monospace; font-size: 12px; }
            pre { background-color: #f1f5f9; padding: 12px; border-radius: 6px; overflow-x: auto; }
            .header-banner { background-color: #0f172a; color: white; padding: 20px; border-radius: 8px; margin-bottom: 30px; }
            .header-banner h1 { color: white; border: none; margin: 0; padding: 0; }
          </style>
        </head>
        <body>
          <div class="header-banner">
            <h1>Source-Grounded Research Report</h1>
            <p style="font-size: 12px; color: #94a3b8; margin-top: 6px;">
              Generated by Source-Grounded Research & Writing Assistant • ${new Date().toLocaleDateString()}
            </p>
          </div>
          ${printContent}
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 500);
  };

  const scrollToSection = (headerName: string) => {
    setActiveSection(headerName);
    const elements = document.querySelectorAll('h1, h2, h3');
    for (let i = 0; i < elements.length; i++) {
      const el = elements[i] as HTMLElement;
      if (el.innerText.toLowerCase().includes(headerName.toLowerCase())) {
        el.scrollIntoView({ behavior: 'smooth', block: 'start' });
        break;
      }
    }
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl space-y-6" id="report-viewer-card">
      {/* Quality Audit Banner */}
      <div className="bg-emerald-950/40 border border-emerald-800/50 rounded-xl p-4 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
        <div className="flex items-center space-x-3">
          <div className="p-2.5 bg-emerald-500/10 text-emerald-400 rounded-lg shrink-0">
            <CheckCircle2 className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center space-x-2">
              <h3 className="text-sm font-semibold text-emerald-200">
                Source Grounding Quality Verification
              </h3>
              <span className="text-[10px] bg-emerald-500/20 text-emerald-300 font-bold px-2 py-0.5 rounded uppercase">
                Passed 100%
              </span>
            </div>
            <p className="text-xs text-slate-300 mt-0.5">
              Verified: All claims are explicitly backed by uploaded sources. Zero hallucinated references.
            </p>
          </div>
        </div>

        <div className="flex items-center space-x-2 shrink-0 self-end sm:self-auto">
          <button
            onClick={handleCopy}
            className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-medium rounded-lg border border-slate-700 flex items-center space-x-1.5 transition-colors"
            id="btn-copy-report"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied!' : 'Copy'}</span>
          </button>

          <button
            onClick={handleDownloadMarkdown}
            className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-medium rounded-lg border border-slate-700 flex items-center space-x-1.5 transition-colors"
            id="btn-download-md"
          >
            <FileCode className="w-3.5 h-3.5 text-indigo-400" />
            <span>Markdown</span>
          </button>

          <button
            onClick={handlePrintPdf}
            className="px-3 py-1.5 bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold rounded-lg flex items-center space-x-1.5 shadow-sm transition-colors"
            id="btn-export-pdf"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Export / Print PDF</span>
          </button>
        </div>
      </div>

      {/* Quick Navigation Jump Bar */}
      <div className="space-y-2">
        <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider flex items-center space-x-1">
          <BookOpen className="w-3.5 h-3.5 text-indigo-400" />
          <span>Jump to Section</span>
        </p>
        <div className="flex flex-wrap gap-1.5 bg-slate-950/60 p-2.5 rounded-xl border border-slate-800/80">
          {SECTION_HEADERS.map((section) => (
            <button
              key={section}
              onClick={() => scrollToSection(section)}
              className={`text-xs px-2.5 py-1 rounded-lg border transition-colors ${
                activeSection === section
                  ? 'bg-indigo-600 text-white border-indigo-500'
                  : 'bg-slate-800/80 hover:bg-slate-700 text-slate-300 border-slate-700/60'
              }`}
            >
              {section}
            </button>
          ))}
        </div>
      </div>

      {/* Main Rendered Document */}
      <div
        ref={printRef}
        className="bg-slate-950 border border-slate-800 rounded-xl p-6 sm:p-8 text-slate-200 prose prose-invert max-w-none prose-headings:text-slate-100 prose-headings:font-bold prose-h1:text-xl prose-h1:border-b prose-h1:border-slate-800 prose-h1:pb-2 prose-h1:mt-8 prose-h2:text-lg prose-h2:text-indigo-300 prose-a:text-indigo-400 prose-strong:text-slate-100 prose-table:border prose-table:border-slate-800 prose-th:bg-slate-900 prose-th:p-3 prose-td:p-3 prose-td:border-t prose-td:border-slate-800/80"
        id="report-markdown-content"
      >
        <ReactMarkdown remarkPlugins={[remarkGfm]}>
          {reportMarkdown}
        </ReactMarkdown>
      </div>

      {/* Footer Reset & Source Info */}
      <div className="flex items-center justify-between border-t border-slate-800 pt-4 text-xs text-slate-400">
        <div className="flex items-center space-x-2">
          <Info className="w-4 h-4 text-indigo-400" />
          <span>Citing {documentNames.length} uploaded document(s)</span>
        </div>

        <button
          onClick={onReset}
          className="text-xs text-indigo-400 hover:text-indigo-300 underline font-medium"
          id="btn-new-research"
        >
          Start New Research Report
        </button>
      </div>
    </div>
  );
};
